/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-07-10 11:59:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Z6Student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Student_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link id=\"mycss\" href=\"../css/add.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link id=\"mycss\" href=\"css/table.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar user={}\r\n");
      out.write("\tuser.$=function(id){\r\n");
      out.write("\t\treturn document.getElementById(id);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction updateData(){\r\n");
      out.write("\t\tuser.$(\"ptel\").style.display=\"none\";\r\n");
      out.write("\t\tuser.$(\"intel\").style.display=\"inline\";\r\n");
      out.write("\t\tuser.$(\"pemail\").style.display=\"none\";\r\n");
      out.write("\t\tuser.$(\"inemail\").style.display=\"inline\";\r\n");
      out.write("\t\tuser.$(\"upd\").style.display=\"none\";\r\n");
      out.write("\t\tuser.$(\"save\").style.display=\"inline\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction queryData(){\r\n");
      out.write("\t\tuser.$(\"t421\").style.display=\"inline\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction personalInfo(forword){\r\n");
      out.write("\t\tvar path =  \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/StudentUpdateServlet?oper=\"+forword;\r\n");
      out.write("\t\tvar reqData\t= {}\r\n");
      out.write("\t\tif (forword === \"updData\"){\r\n");
      out.write("\t\t\tconsole.log(\"执行更新 发送的数据\");\r\n");
      out.write("\t\t\treqData = {\r\n");
      out.write("\t\t\t\t\t\ttelephone:$(\"#intel\").val(),\r\n");
      out.write("\t\t\t\t\t\temail:$(\"#inemail\").val()\r\n");
      out.write("\t\t\t\t\t  };\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tconsole.log(\"执行 personalInfo \" + forword);\r\n");
      out.write("\t\t$.post(\r\n");
      out.write("\t\t\t\t\tpath,\r\n");
      out.write("\t\t\t\t\treqData,\r\n");
      out.write("\t\t\t\t\tfunction(data){\r\n");
      out.write("\t\t\t\t\t\tvar info=\"\";\r\n");
      out.write("\t\t\t\t\t\tvar user=eval(data);\r\n");
      out.write("\t\t\t\t\t\tinfo = \"<form name=\\\"myfm\\\">\";\r\n");
      out.write("\t\t\t\t\t\tinfo += \"<table id=\\\"t1\\\">\";\r\n");
      out.write("\t\t\t\t\t\t$.each(user,function(i){\r\n");
      out.write("\t\t\t\t\t\t\tif(user[i].id != \"\"){ \r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<tr><td class=\\\"td1\\\">姓名：</td><td>\"+user[i].name+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<tr><td>学号：</td><td>\"+user[i].id+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<tr><td>性别：</td><td>\"+user[i].sex+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<tr><td>出生日期：</td><td>\"+user[i].birthday+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<tr><td>手机号码：</td><td><p id=\\\"ptel\\\" name=\\\"tel\\\">\"+user[i].telephone+\"</p>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<input type=\\\"text\\\" id=\\\"intel\\\" name=\\\"tel\\\" value=\\\"\"+user[i].telephone+\"\\\" style=\\\"display:none\\\"></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<tr><td>邮箱：</td><td><p id=\\\"pemail\\\" name=\\\"email\\\">\"+user[i].email+\"</p>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<input type=\\\"text\\\" id=\\\"inemail\\\" name=\\\"email\\\" value=\\\"\"+user[i].email+\"\\\" style=\\\"display:none\\\"></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<tr><td>所在班级：</td><td>\"+user[i].classId+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tif(forword == \"show\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<tr><td><input type=\\\"button\\\" id=\\\"upd\\\" value=\\\"修改\\\" onclick=\\\"return updateData()\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<input type=\\\"button\\\" id=\\\"save\\\"  value=\\\"保存\\\" style=\\\"display:none\\\" onclick=\\\"personalInfo('updData')\\\" ></td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<td><input type=\\\"button\\\" value=\\\"重置\\\" onclick=\\\"myfm.reset()\\\"></td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo=\"操作有误\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tinfo+=\"</table>\"; \r\n");
      out.write("\t\t\t\t\t\tinfo+=\"</form>\"; \r\n");
      out.write("\t\t\t\t\t\t$(\"#d41\").html(\"个人信息修改\")\r\n");
      out.write("\t\t\t\t\t\t$(\"#d42\").html(info);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(\"保存按钮value\" + document.getElementById(\"save\").value);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\"JSON\"\r\n");
      out.write("\t\t\t)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getQueryData(forword){\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\tvar urlPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/StudentQueryServlet?action=\"+forword;\r\n");
      out.write("\t\tvar requestObj = \"\";\r\n");
      out.write("\t\tdocument.getElementById(\"t421\").style.display=\"inline\";\r\n");
      out.write("\t\tif(forword == \"conditions\"){\r\n");
      out.write("\t\t\trequestObj = {\r\n");
      out.write("\t\t\t\t\t\t\teecId:$(\"#eecId\").val(),\r\n");
      out.write("\t\t\t\t\t\t\teecName:$(\"#eecName\").val(),\r\n");
      out.write("\t\t\t\t\t\t\troleName:$(\"#roleName\").val()\r\n");
      out.write("\t\t\t\t\t\t };\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.post(\r\n");
      out.write("\t\t\t\turlPath,\r\n");
      out.write("\t\t\t\trequestObj,\t\r\n");
      out.write("\t\t\t\tfunction(data){\r\n");
      out.write("\t\t\t\t\tvar info=\"\";\r\n");
      out.write("\t\t\t\t\tvar user=eval(data);\r\n");
      out.write("\t\t\t\t\tinfo=\"<table id=\\\"t2\\\" border=\\\"1\\\">\";\r\n");
      out.write("\t\t\t\t\tinfo+=\"<tr bgcolor=\\\"#8FBC8F\\\">\";\r\n");
      out.write("\t\t\t\t\tinfo+=\"<td>序号</td><td>班级</td><td>学号</td><td>姓名</td><td>性别</td>\";\r\n");
      out.write("\t\t\t\t\tinfo+=\"<td>出生日期</td><td>手机号</td><td>邮箱</td><td>职务</td>\";\r\n");
      out.write("\t\t\t\t\tinfo+=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t$.each(user,function(i){\r\n");
      out.write("\t\t\t\t\t\tif(user[i].id != \"\"){ \r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<tr><td>\"+(i+1)+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<td>\"+user[i].classId+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<td>\"+user[i].id+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<td>\"+user[i].name+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<td>\"+user[i].sex+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<td>\"+user[i].birthday+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<td>\"+user[i].telephone+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<td>\"+user[i].email+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<td>\"+user[i].roleName+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tinfo+=\"<tr><td colspan=\\\"9\\\">未找到符合条件的数据</td></tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tinfo+=\"</table>\"; \r\n");
      out.write("\t\t\t\t\t$(\"#d41\").html(\"班级信息查询\")\r\n");
      out.write("\t\t\t\t\t$(\"#d422\").html(info);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"JSON\"\r\n");
      out.write("\t\t\t)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#d31\").click(function(){\r\n");
      out.write("\t\t\tpersonalInfo(\"show\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t/* $(\"#save\").click(function(){\r\n");
      out.write("\t\t\tconsole.log(\"save  111111111\");\r\n");
      out.write("\t\t\tpersonalInfo(\"updData\");\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\t\t$(\"#d32\").click(function(){\r\n");
      out.write("\t\t\tgetQueryData(\"classId\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#cond\").click(function(){\r\n");
      out.write("\t\t\tgetQueryData(\"conditions\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#F5FFFA\">\r\n");
      out.write("\t<div id=\"d0\">\r\n");
      out.write("\t\t<h1>学生信息综合管理系统</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"d1\">\r\n");
      out.write("\t\t<div id=\"d2\">&nbsp;&nbsp;&nbsp;当前用户:学生\r\n");
      out.write("\t\t<div id=\"d21\">\r\n");
      out.write("\t\t\t<a href=\"#\">首页</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<a href=\"#\">退出登录</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"d3\">\r\n");
      out.write("\t\t\t<div id=\"d31\">个人基本信息管理</div>\r\n");
      out.write("\t\t\t<div id=\"d32\">班级信息查询</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"d4\">\r\n");
      out.write("\t\t\t<div id=\"d41\">个人资料展示</div>\r\n");
      out.write("\t\t\t<div id=\"d42\">\r\n");
      out.write("\t\t\t\t<table id=\"t421\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;&nbsp;学号：<input type=\"text\" id=\"eecId\" name=\"eecId\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;&nbsp;姓名：<input type=\"text\" id=\"eecName\" name=\"eecName\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;&nbsp;职务：\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"roleName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>学生</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>组长</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>班长</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>任课老师</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>班主任</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>&nbsp;&nbsp;<input type=\"button\" id=\"cond\" value=\"查 询\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div id=\"d422\"> \r\n");
      out.write("\t\t\t\t\t<form name=\"myfm\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /Z6Student/Student.jsp(185,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<table id=\"t1\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td class=\"td1\">姓名：</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>学号：</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>性别：</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t");
        if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>出生日期：</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.birthday}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>手机号码：</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<p id=\"ptel\" name=\"tel\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.telephone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"intel\" name=\"tel\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.telephone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" style=\"display:none\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>email：</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<p id=\"pemail\" name=\"email\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</p>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"inemail\" name=\"email\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" style=\"display:none\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>所在班级：</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.classId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"upd\" value=\"修改\" onclick=\"return updateData()\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input style=\"display:none\" type=\"button\" id=\"save\" value=\"保存\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"button\" value=\"重置\" onclick=\"myfm.reset()\"></td>\r\n");
        out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t\t\t</table>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /Z6Student/Student.jsp(198,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.sex eq '男'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"男\" checked=\"checked\">男\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"女\">女\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /Z6Student/Student.jsp(202,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.sex eq '女'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"男\">男\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"女\" checked=\"checked\">女\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
