/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-06-24 05:29:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Z6Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.chinasofti.eecuser.model.javabean.UserInfo;

public final class TeacherAdd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link id=\"mycss\" href=\"../css/add.css\" rel=\"stylesheet\" type=\"text/css\"/> \n");
      out.write("</head>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-1.7.2.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar THE_THEACHER_ROLEID = 3004;\n");
      out.write("\tvar HEAD_THEACHER_ROLEID = 3005;\n");
      out.write("\t\n");
      out.write("\tfunction getCustomPageIndex(){\n");
      out.write("\t\treturn document.getElementById(\"pageIndex\").value;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction showInfo(){\n");
      out.write("\t\tconsole.log(\"id :\" + $(\"#id\").val());\n");
      out.write("\t\tconsole.log(\"name :\" + $(\"#name\").val());\n");
      out.write("\t}\n");
      out.write("\tfunction appointTheacher(eecId, classIdELM, \n");
      out.write("\t\t\ttheTheacherELM,headTheacherELM,  trIdELM){\n");
      out.write("\t\tconsole.log(classIdELM);\n");
      out.write("\t\tconsole.log($(classIdELM).val());\n");
      out.write("\t\tconsole.log(\"theTheacher check  \");\n");
      out.write("\t\tconsole.log($(theTheacherELM).prop(\"checked\"));\n");
      out.write("\t\tconsole.log(\"headTheacher check  \");\n");
      out.write("\t\tconsole.log($(headTheacherELM).prop(\"checked\"));\n");
      out.write("\t\tvar theacherType;\n");
      out.write("\t\tif($(theTheacherELM).prop(\"checked\")){\n");
      out.write("\t\t\ttheacherType = $(theTheacherELM).val()\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\ttheacherType = $(headTheacherELM).val()\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t$.post(\n");
      out.write("\t\t\t\t\"");
      out.print(request.getContextPath());
      out.write("/AdminServlet\",\t\t\t\t\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\taction:\"addTheacherTrue\",\n");
      out.write("\t\t\t\t\tclassId:$(classIdELM).val(),\n");
      out.write("\t\t\t\t\ttheacherType:theacherType,\n");
      out.write("\t\t\t\t\tid:eecId\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tfunction(data){\n");
      out.write("\t\t\t\t\tif(data==\"success\"){\n");
      out.write("\t\t\t\t\t\tvar classSelect = trIdELM + \" td:eq(7)\";\n");
      out.write("\t\t\t\t\t\tvar teacherTypeSelect = trIdELM + \" td:eq(8)\";\n");
      out.write("\t\t\t\t\t\t$(classSelect).html($(classIdELM).val()); // 设定班级\n");
      out.write("\t\t\t\t\t\tif(theacherType == THE_THEACHER_ROLEID){\n");
      out.write("\t\t\t\t\t\t\t$(teacherTypeSelect).html(\"任课老师\");\n");
      out.write("\t\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t\t$(teacherTypeSelect).html(\"班主任\");\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\tconsole.log(\"更新失败\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction getEecUserInfo(forward){\n");
      out.write("\t\tshowInfo();\n");
      out.write("\t\t$.post(\n");
      out.write("\t\t\t\t\"");
      out.print(request.getContextPath());
      out.write("/AdminServlet\",\t\t\t\t\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\taction:\"addTheacher\",\n");
      out.write("\t\t\t\t\t// 分页对象存储在session中的key， 本来考虑通过传参，锁定不同的分页对象，\n");
      out.write("\t\t\t\t\t// 不同人需求不同，暂时先各自按自己key分页\n");
      out.write("\t\t\t\t\tsqlPageHashMap:\"addTeacherPage\",  \n");
      out.write("\t\t\t\t\tpageIndex: forward, // 页面跳转参数\n");
      out.write("\t\t\t\t\tid:$(\"#id\").val(),\n");
      out.write("\t\t\t\t\tname:$(\"#name\").val()\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tfunction(data){\n");
      out.write("\t\t\t\t\t//console.log(\"数据解析支持成功\");\n");
      out.write("\t\t\t\t\tvar eecUsers = eval(data);\n");
      out.write("\t\t\t\t\tvar htmlData = \"\";\n");
      out.write("\t\t\t\t\tvar classNamesHtml = \"\";\n");
      out.write("\t\t\t\t\thtmlData +=\t'<tr bgcolor=\"#8FBC8F\">';\n");
      out.write("\t\t\t\t\thtmlData += '<td>序号</td><td>学号</td><td>姓名</td><td>性别</td><td>年龄</td>';\n");
      out.write("\t\t\t\t\thtmlData += '<td>邮箱</td><td>手机号</td><td>班级选择</td><td>操作</td>';\n");
      out.write("\t\t\t\t\thtmlData += '</tr>';\n");
      out.write("\t\t\t\t\tif(eecUsers == null || eecUsers.length == 0){\n");
      out.write("\t\t\t\t\t\thtmlData += \"<tr >\";\n");
      out.write("\t\t\t\t\t\thtmlData += '<td colspan=\"12\">没有获取到数据</td>';\n");
      out.write("\t\t\t\t\t\thtmlData += \"</tr>\";\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t$.each(eecUsers ,function(i){\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"<tr id=\\\"usd\" + (i+1) + \"\\\">\";\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"<td>\" + (i+1)  +\"</td>\";\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"<td>\" + eecUsers[i].id  +\"</td>\";\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"<td>\" + eecUsers[i].name  +\"</td>\";\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"<td>\" + eecUsers[i].sex  +\"</td>\";\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"<td>\" + eecUsers[i].age  +\"</td>\";\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"<td>\" + eecUsers[i].email  +\"</td>\";\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"<td>\" + eecUsers[i].telephone  +\"</td>\";\n");
      out.write("\t\t\t\t\t\t\tif(i==0){\n");
      out.write("\t\t\t\t\t\t\t\tfor(var j=0; j<eecUsers[i].classNames.length;j++){\n");
      out.write("\t\t\t\t\t\t\t\t\tclassNamesHtml +='<option value=\"' + eecUsers[i].classNames[j] \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+'\">'+ eecUsers[i].classNames[j]  +'</option>';\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\thtmlData += '<td><select name=\"className\" id=\"className' + (i+1) + '\" >' + classNamesHtml + '</select></td>';\n");
      out.write("\t\t\t\t\t\t\thtmlData += '<td><span>任课老师</span><input type=\"radio\" id=\"theTheacher' + (i+1) + '\" name=\"theacherType\"  value=\"'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ THE_THEACHER_ROLEID +'\"  /><span>班主任</span>'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<input type=\"radio\" id=\"headTheacher' + (i+1) + '\" name=\"theacherType\"  value=\"'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ HEAD_THEACHER_ROLEID +'\"  />'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '<input type=\"button\" value=\"确认选择\" onclick=\"appointTheacher(' + eecUsers[i].id  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ ',\\'#className' + (i+1)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ '\\',\\'#theTheacher' + (i+1)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ '\\',\\'#headTheacher' + (i+1)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ '\\',\\'#usd' + (i+1) + '\\')\" ></td>';\n");
      out.write("\t\t\t\t\t\t\thtmlData += \"</tr>\";\n");
      out.write("\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\thtmlData +=  '<td colspan=\"2\"><input type=\"button\"  onclick=\"getEecUserInfo(\\'first\\')\" value=\"首页\" ></td>';\n");
      out.write("\t\t\t\t\t\thtmlData +=  '<td colspan=\"2\"><input type=\"button\"  onclick=\"getEecUserInfo(\\'pre\\')\" value=\"前页\" ></td>';\n");
      out.write("\t\t\t\t\t\thtmlData +=  '<td colspan=\"2\"><input type=\"button\"  onclick=\"getEecUserInfo(\\'next\\')\" value=\"次页\" ></td>';\n");
      out.write("\t\t\t\t\t\thtmlData +=  '<td colspan=\"2\"><input type=\"button\"  onclick=\"getEecUserInfo(\\'last\\')\" value=\"尾页\" ></td>';\n");
      out.write("\t\t\t\t\t\thtmlData +=  '<td colspan=\"2\"><input type=\"number\" id=\"pageIndex\">';\n");
      out.write("\t\t\t\t\t\thtmlData +=  '<input type=\"button\" onclick=\"getEecUserInfo(getCustomPageIndex())\" value=\"指定页\" ></td>';\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t$(\"#t2\").html(htmlData);\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\t\"JSON\"\n");
      out.write("\t\t\t);\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t$(function(){\n");
      out.write("\t\t$(\"#query\").click(function(){\n");
      out.write("\t\t\tgetEecUserInfo(\"first\");\n");
      out.write("\t\t})\n");
      out.write("\t})\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");

		final int ADMIN_ROLEID = 3006;	
		final int THE_THEACHER_ROLEID = 3004;
		final int HEAD_THEACHER_ROLEID = 3005;
		int [] classNames = {20170207, 20170208, 20170209,20170210};
		// 登录信息暂时没有的情况，自己先做一个数据保证程序运行
		UserInfo stu = new UserInfo(20170207, 170000002, "管理员", "男",
				88,  "4437074544@qq.com", 11593239991L, 3006);
		session.setAttribute("userInfo", stu);
		UserInfo admin = (UserInfo)session.getAttribute("userInfo");
		if(admin==null){
			//request.getRequestDispatcher("NoLogin.jsp").forward(request, response);
			return;
		}
		// 这一步判断可以去掉，肖梦娜使用过滤器做， 对应的权限只能访问对应的目录
		if(admin.getRoleId()!=ADMIN_ROLEID){
			//request.getRequestDispatcher("NoLogin.jsp").forward(request, response);
			return;	
		}
		request.setAttribute("theTheacher", THE_THEACHER_ROLEID);
		request.setAttribute("headTheacher", HEAD_THEACHER_ROLEID);
		request.setAttribute("classNames", classNames);
	
      out.write("\n");
      out.write("\t<div id=\"d0\">\n");
      out.write("\t\t<h1>学生信息综合管理系统</h1>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"d1\">\n");
      out.write("\t\t<div id=\"d2\">&nbsp;&nbsp;&nbsp;当前用户:学生\n");
      out.write("\t\t<div id=\"d21\">\n");
      out.write("\t\t\t<a href=\"#\">首页</a>&nbsp;&nbsp;&nbsp;\n");
      out.write("\t\t\t<a href=\"#\">退出登录</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"d3\">\n");
      out.write("\t\t\t<div id=\"d31\"><a href=\"#\">个人信息</a></div>\n");
      out.write("\t\t\t<div id=\"d32\"><a href=\"ClassManage.jsp\">班级管理</a></div>\n");
      out.write("\t\t\t<div id=\"d33\"><a href=\"TeacherManage.jsp\">教师信息查看</a></div>\n");
      out.write("\t\t\t<div id=\"d34\"><a href=\"TeacherAdd.jsp\">添加教师</a></div>\n");
      out.write("\t\t\t<div id=\"d35\"><a href=\"TeacherDEL.jsp\">罢免教师</a></div>\n");
      out.write("\t\t\t<div id=\"d36\"><a href=\"TeacherUPD.jsp\">教师信息更改</a></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"d4\">\n");
      out.write("\t\t\t<div id=\"d41\">添加教师</div>\n");
      out.write("\t\t\t<table id=\"t1\" >\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;学号：<input type=\"text\"  name=\"id\" value=\"\"></td>\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;姓名：<input type=\"text\" name=\"name\" value=\"\"></td>\n");
      out.write("\t\t\t\t\t<!-- 默认全部查询 -->\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;<input type=\"button\" id=\"query\" name=\"query\" value=\"查 询\"></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t<table id=\"t2\" border=\"1\">\n");
      out.write("\t\t\t\t<tr bgcolor=\"#8FBC8F\">\n");
      out.write("\t\t\t\t\t<td>序号</td><td>学号</td><td>姓名</td><td>性别</td><td>年龄</td>\n");
      out.write("\t\t\t\t\t<td>邮箱</td><td>手机号</td><td>班级选择</td><td colspan=\"3\">操作</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td></td><td></td><td></td><td></td><td></td>\n");
      out.write("\t\t\t\t\t<td></td><td></td><td></td>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<select name=\"className\" >\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<span>任课老师</span>\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"theacherType\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.theTheacher }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  />\n");
      out.write("\t\t\t\t\t\t<span>班主任</span>\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"theacherType\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.headTheacher }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  />\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"确认选择\" onclick=\"\" >\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /Z6Admin/TeacherAdd.jsp(201,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("className");
    // /Z6Admin/TeacherAdd.jsp(201,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.classNames }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${className }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${className }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
