/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-06-21 12:31:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.study.mvc.model.bean.StudentInfo;
import java.util.List;
import com.study.mvc.model.bean.UserInfo;

public final class UserList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- uri:标签库描述文件所在位置 -->\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>具体功能页面</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"Myjs/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction delArm(){\r\n");
      out.write("\t\tif(confirm(\"确认要删除吗？\")){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction pageNumberS(){\r\n");
      out.write("\t\treturn document.getElementById('pagenum').value;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function getBodyData(forword){\r\n");
      out.write("    \talert('forword:'+forword);\r\n");
      out.write("\t\t$.post(\r\n");
      out.write("\t\t\t\"getDataAction?page=\"+forword,\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfindCondition:$(\"#stuname\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfunction(data){\t\r\n");
      out.write("\t\t\t\t//将Json转换为Js数组对象\r\n");
      out.write("\t\t\t\tvar students=eval(data);\r\n");
      out.write("\t\t\t\tvar htmStr=\"\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<table border=\\\"3\\\">\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<caption>学员信息一览</caption>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<tr><td>序号</td><td>学号</td><td>姓名</td><td>性别</td><td>年龄</td><td>毕业院校</td><td colspan=\\\"2\\\">操作</td></tr>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//如何使用Jquery解析XML中的数据\r\n");
      out.write("\t\t\t\t//用Jquery方法each遍历该数组对象，尤其注意遍历规则函数的写法\r\n");
      out.write("\t\t\t\t$.each(students,function(i){\r\n");
      out.write("\t\t\t\t\tif(students[i].id==\"\"){\r\n");
      out.write("\t\t\t\t\t\thtmStr+=\"<tr>\";\r\n");
      out.write("\t\t\t\t\t\thtmStr+=\"<td colspan=\\\"8\\\">没有符合条件的数据</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<tr>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+(i+1)+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+students[i].id+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+students[i].name+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+students[i].sex+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+students[i].age+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+students[i].gradeFrom+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td><a href=\\\"QueryServlet?action=getStuByID&id=\"+students[i].id+\"\\\">修改</a></td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td><a href=\\\"UpdateServlet?action=stu_del&id=\"+students[i].id+\"\\\" onclick=\\\"return delArm()\\\">删除</a></td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\thtmStr+=\"<tr>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td colspan='2'><input type=\\\"button\\\" value='首页' onclick='getBodyData(\\\"first\\\")'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td colspan='2'><input type=\\\"button\\\" value='前页' onclick='getBodyData(\\\"pre\\\")'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td colspan='2'><input type=\\\"button\\\" value='次页' onclick='getBodyData(\\\"nxt\\\")'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td><input type=\\\"button\\\" value='尾页' onclick='getBodyData(\\\"last\\\")'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td><input type=\\\"button\\\" value='指定页' onclick='getBodyData(pageNumberS())'><input type='number' id='pagenum'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"</table>\";\r\n");
      out.write("\t\t\t\t//首页 前页 次页 尾页\r\n");
      out.write("\t\t\t\t//<input type=\"button\" value=\"首页\" onclick=\"getBodyData()\">\r\n");
      out.write("\t\t\t\t//alert(htmStr)\r\n");
      out.write("\t\t\t\t//alert(htmStr);\r\n");
      out.write("\t\t\t\t$(\"#tbl\").html(htmStr);\t\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"JSON\"\r\n");
      out.write("\t\t);\r\n");
      out.write("    }\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#search\").click(function(){\r\n");
      out.write("\t\t\tgetBodyData('first');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t欢迎您，");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userInfo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("    <form action=\"\" >\r\n");
      out.write("\t\t<table border=\"3\">\r\n");
      out.write("\t\t    <caption>学员信息查询处理</caption>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t       <td>姓名：</td><!--模糊查询-->\r\n");
      out.write("\t\t       <td><input type=\"text\" name=\"stuname\" id=\"stuname\"></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t       <td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("\t\t       \t\t<input type=\"button\" id=\"search\" value=\"查询\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t       \t\t<input type=\"button\" id=\"clear\" value=\"重置查询\" onclick=\"\">\r\n");
      out.write("\t\t       \t</td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("    </form>\r\n");
      out.write("    <!-- Ajax需要刷新的区域 -->\r\n");
      out.write("    <div id=\"tbl\"></div>\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /UserList.jsp(92,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty requestScope.msg}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t<div style=\"color: red\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</div>\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /UserList.jsp(114,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty maxp}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t    ");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /UserList.jsp(115,5) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setBegin(1);
    // /UserList.jsp(115,5) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maxp}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
    // /UserList.jsp(115,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("nun");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t    \t<a href=\"#\" onclick=\"getBodyData(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nun}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(')');
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nun}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\r\n");
          out.write("\t    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
